### ISSUE TITLE
"ERROR: subtokenization failed" when evaluating

### ISSUE THREAD

**Issue by SamySam0** [BCHSI/philter-deidstable1_mirror#4]
Hello,

When running the following command, on the v1.2024.1 release : 
```python 
!python3 deidpipe.py -i ../my_data/ -o ../my_results/ -f configs/philter_one2024.json -d False -e True -a ../../drive/MyDrive/***/data/spec
```

with only the attached .txt file in ../my_data/ and the attached .xml file in ../../drive/MyDrive/***/data/spec, I get the following error:

``` 
Running eval
{'start': 573, 'length': 1, 'stop': 573, 'token': 'V', 'phitype': 'DOCTOR'} {'start': 574, 'stop': 582, 'length': 9, 'token': 'andenberg'} {'start': 583, 'length': 1, 'stop': 583, 'token': 'g', 'phitype': 'NAME'}
Traceback (most recent call last):
  File "/content/philter/src/phitexts.py", line 1312, in _update_with_sub_tokens
    subtokens = self._get_sub_tokens(gold, philter)
  File "/content/philter/src/phitexts.py", line 1188, in _get_sub_tokens
    raise Exception("ERROR: string mismatch: \"" + middle['token']
Exception: ERROR: string mismatch: "andenberg" != "Vandenber" in tokens: "Vandenberg" (573-582) and "Vandenberg" (574-583)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/philter/src/deidpipe.py", line 193, in <module>
    sys.exit(main())
  File "/content/philter/src/deidpipe.py", line 109, in main
    main_mongo(args)
  File "/content/philter/src/deidpipe.py", line 187, in main_mongo
    phitexts.eval(args.anno, args.output)
  File "/content/philter/src/phitexts.py", line 1442, in eval
    self._update_with_sub_tokens(gold_dicts, philter_dicts)
  File "/content/philter/src/phitexts.py", line 1314, in _update_with_sub_tokens
    raise Exception("ERROR: subtokenization failed for "
Exception: ERROR: subtokenization failed for ../data/236-01.txt: ERROR: string mismatch: "andenberg" != "Vandenber" in tokens: "Vandenberg" (573-582) and "Vandenberg" (574-583)
/content 
```

[236-01.txt](https://github.com/user-attachments/files/16820658/236-01.txt)
[236-01.xml.txt](https://github.com/user-attachments/files/16820659/236-01.xml.txt) (I changed it to .txt to upload it here)

**Comment by RedChrists** [comment]
What you are seeing is an error caused by a slightly erroneous tag in the XML file. I have seen this with a few of the I2B2 XML files when the tagged text spans a newline. For some reason the newline was not included as whitespace in the text field. If you count the number of characters that should be included in the tag according to the start and end values you will see what I mean. To fix this you can add an extra space in the tag where the newline is in the text:
`<NAME id="P8" start="562" end="584" text="Peter       Vandenberg" TYPE="DOCTOR" comment="" />`
`<NAME id="P14" start="2618" end="2640" text="Peter       Vandenberg" TYPE="DOCTOR" comment="" />`
